name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:

    # Unfortunately, GitHub silently ignores, if we set it to macos-10.14,
    # which is what we actually want. :-/
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 9
          architecture: x64

      - name: Build/test code with Maven
        shell: bash
        # Manipulate TCC, see https://github.com/actions/virtual-environments/issues/553#issuecomment-648109166
        # in order to allow AppleScript automation of iTunes.app
        run: |
          sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 1, 1, 0, 'com.apple.iTunes')"
          mvn -B install --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
